theme = "tokyonight"

[editor]
line-number = "relative"
text-width = 120
popup-border = "all"
color-modes = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
center = ["version-control"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-y = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"
"$" = "goto_line_end"
0 = "goto_line_start"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
x = "delete_selection"

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
